#!/bin/sh

# a bashrc (bash_profile on OSX)
# also for my 64bit cygwin

# if not interactive, don't setup
[ -z "$PS1" ] && return

if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

# python aliases
alias pt='python3 -m doctest'
alias p='python3'
alias pi='python3 -i'
alias p2='python2.7'
alias p2t='python2.7 -m doctest'

# looking for errors
function ptgrep {
    # first param file name
    # second param pattern to look for
    pt $1 | grep -A 10 -n $2 | less
}

# pretty lists and view hidden
alias ll="ls -lAsGh"

# custom prompt with git branch
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWCOLORHINTS=true
GIT_PS1_SHOWUPSTREAM="auto"
source ~/bin/git-prompt.sh
# need to add the virtualenv thing back in
    PURPLE="\[\033[1;34m\]"
    YELLOW="\[\033[1;33m\]"
 LIGHT_RED="\[\033[1;31m\]"
COLOR_NONE="\[\033[0m\]"
# export PS1='\[\e[0;33m\]\u@\h:\W\[\e[0;33m\]$(__git_ps1 " (%s)") \$\[\e[m\] '
function set_prompt_symbol () {
	if test $1 -eq 0 ; then
		PROMPT_SYMBOL="\$"
	else
		PROMPT_SYMBOL="${LIGHT_RED}\$${COLOR_NONE}"
	fi
}
function set_virtualenv () {
	if test -z "$VIRTUAL_ENV" ; then
		PYTHON_VIRTUALENV=""
	else
		PYTHON_VIRTUALENV="${PURPLE}venv ${COLOR_NONE}"
	fi
}
function set_bash_prompt() {
	# Set the PROMPT_SYMBOL variable. We do this first so we don't lose the
	# return value of the last command.
	set_prompt_symbol $?

	set_virtualenv

	BASH_PROMPT="${PYTHON_VIRTUALENV}${YELLOW}\u@\h:\w${COLOR_NONE}"
}
PROMPT_COMMAND='update_terminal_cwd; set_bash_prompt ; __git_ps1 "$BASH_PROMPT" "${YELLOW}${PROMPT_SYMBOL}${COLOR_NONE} "'

# add ~/bin to the path
# this ought to be in bashrc so noninteractive shells get this too
PATH=$PATH\:~/bin\:$HOME/.local/bin

# start ssh-agent
eval $(ssh-agent) &>/dev/null

# git aliases
alias gitpull='ssh-add && git pull'
alias gitpullr='ssh-add && git pull --rebase'

if [[ "$(uname)" == CYGWIN* ]]; then
	alias subl="/cygdrive/c/Program\ Files/Sublime\ Text\ 3/sublime_text.exe"
else
	# tab completion for git, which is already included in cygwin
	source ~/bin/git-completion.bash
fi
# for vim
stty -ixon
