#!/bin/sh

# a bashrc (bash_profile on OSX)
# also for my 64bit cygwin

# python aliases
alias pt='python3 -m doctest -v'
alias p='python3'
alias pi='python3 -i'
alias p2='python2.7'

# looking for errors
function ptgrep {
    # first param file name
    # second param pattern to look for
    pt $1 | grep -A 10 -n $2 | less
}

# alias for cs61c-db login
alias sshcs='ssh cs61c-db@hive5.cs.berkeley.edu'
# scp files into specified folder
HIVE='cs61c-db@hive1.cs.berkeley.edu:~'
function scpcs {
    # so $FOLDER turns hw6.py to hw6
	FOLDER=`echo "$1" | cut -d'.' -f1`
	scp $1 $HIVE/$2
}

# pretty lists and view hidden
alias ll="ls -lasGh"
PS1='\[\e[0;33m\]\h:\W \u\$\[\e[m\] '

# add ~/bin to the path

PATH=$PATH\:~/bin

# start ssh-agent
eval $(ssh-agent)