#!/bin/sh

# a bashrc (bash_profile on OSX)
# also for my 64bit cygwin

# if not interactive, don't setup
[ -z "$PS1" ] && return

if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

# python aliases
alias pt='python3 -m doctest -v'
alias p='python3'
alias pi='python3 -i'
alias p2='python2.7'

# looking for errors
function ptgrep {
    # first param file name
    # second param pattern to look for
    pt $1 | grep -A 10 -n $2 | less
}

# pretty lists and view hidden
alias ll="ls -lAsGh"
# custom prompt with git branch
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWCOLORHINTS=true
GIT_PS1_SHOWUPSTREAM="auto"
source ~/bin/git-prompt.sh
# export PS1='\[\e[0;33m\]\u@\h:\W\[\e[0;33m\]$(__git_ps1 " (%s)") \$\[\e[m\] '
GIT_AGORA_PROMPT_COMMAND='__git_ps1 "\[\e[0;33m\]\u@\h:\w\[\e[0m\]" "\[\e[0;33m\]\\\$\[\e[0m\] " ;'
export PROMPT_COMMAND="$PROMPT_COMMAND $GIT_AGORA_PROMPT_COMMAND"

# add ~/bin to the path
# this ought to be in bashrc so noninteractive shells get this too
PATH=$PATH\:~/bin

# start ssh-agent
eval $(ssh-agent) &>/dev/null

# git aliases
alias gitpull='ssh-add && git pull'
alias gitpullr='ssh-add && git pull --rebase'
# tab completion for git
source ~/git/git-completion.bash

if [[ "$(uname)" == CYGWIN* ]]; then
	alias subl="/cygdrive/c/Program\ Files/Sublime\ Text\ 3/sublime_text.exe"
fi
# for vim
stty -ixon
